### PR TITLE
added preserve formatting setting

### PR DESCRIPTION
**Pull request by SocksM**
example:
Screenshot 2024-12-03 014601

### CODE REVIEW

**Comment by SocksM** [comment]
edit: wrong img changed to the correct one

**Comment by Aerhhh** [comment]
Why are we making this a setting when it should be default behaviour to carry over formatting codes?

**Comment by SocksM** [comment]
i would imagine its annoying for dialogue's etc. so though oh well might aswell just make it a setting

**Comment by Aerhhh** [comment]
It should be default behaviour, though I think the way you implemented the preserving of formatting codes is messy

**Pull request closed without merging**
