### PR TITLE
Bug fix preserve formatting

### PR DESCRIPTION
**Pull request by SocksM**
Added a Text Formatting settings class to more easily carry over the settings without any wonky code.
And made formatting get carried over.

### CODE REVIEW

**Comment by SocksM** [comment]
This better be clean enough!

**Comment by SocksM** [comment]
Also, you should really test it yourself because I tried a lot of what could be edge cases that would fail but didn't find anything. However, I'm sure there is probably something that will break it just couldn't think of what would.

**Comment by CraftedFury** [comment]
Alright you need to stop abstracting fields into other classes. In this specific PR the entire change creates a full breaking change to JSON Deserialization/Serialization. The classes model the internal Minecraft JSON structure and can be converted to/from JSON directly as well as directly with Java.

As for expanding a stream into a massive loop, you've changed nothing except make it take longer to understand what it's doing. Stop eliminating streams and please learn how to read them.

**Comment by SocksM** [comment]
Was the idea behind the approach valid tho? Because if so I'll just make it into a stream and remove the formatting class. 

> As for expanding a stream into a massive loop, you've changed nothing except make it take longer to understand what it's doing.
Also, I'm curious why would I use a stream over a loop and the other way around. 
And what do you mean by "understand what it's doing." what is "it" in this case? The code? And if it is the code what does it even need to understand I think I'm missing something here. Is it like trying to optimize it by finding patterns and applying those patterns but this happens more efficiently in streams?

**Comment by Aerhhh** [comment]
https://github.com/SkyBlock-Nerds/NerdBot/commit/4b962093a9b2c71c2742e28bfed15efd59c16291

**Pull request closed without merging**
